// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface IAddressFields {
  /** Name */
  name?: string | undefined;

  /** Unit */
  unit?: string | undefined;

  /** Building */
  building?: string | undefined;

  /** Street */
  street?: string | undefined;

  /** City */
  city?: string | undefined;

  /** Region */
  region?: string | undefined;

  /** Address Code */
  address_code?: string | undefined;

  /** Related Business/Venue */
  related_business_venue: (IBusiness | IVenue)[];

  /** Country */
  country?: string | undefined;
}

/** Address, possibly shared across Business and Venue */

export interface IAddress extends Entry<IAddressFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'address';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IBusinessFields {
  /** Name */
  name?: string | undefined;

  /** Created Date */
  created_date: string;

  /** Owned Venues */
  owned_venues: IVenue[];
}

/** Partnership registered business that owns one or many venues */

export interface IBusiness extends Entry<IBusinessFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'business';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IDealFields {
  /** Title */
  title: string;

  /** Description */
  description: Document;

  /** Currency */
  currency: 'AUD' | 'GBP' | 'EUR' | 'NZD';

  /** Original Price */
  original_price: number;

  /** Discounted Price */
  discounted_price: number;

  /** Redemption Conditions */
  redemption_conditions: Document;

  /** Pax */
  pax: number;

  /** Tags */
  tags?: ('Vegan' | 'Healthy' | 'Popular')[] | undefined;

  /** Total Available */
  total_available?: number | undefined;

  /** Sale Start Date */
  sale_start_date: string;

  /** Sale End Date */
  sale_end_date: string;

  /** Redeem Start Date */
  redeem_start_date: string;

  /** Redeem End Date */
  redeem_end_date: string;

  /** Banner Images */
  banner_images: Asset[];
}

/** Deals that are being promoted by a venue or group of venues */

export interface IDeal extends Entry<IDealFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'deal';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IVenueFields {
  /** Name */
  name: string;

  /** Created Date */
  created_date: string;

  /** Categories */
  categories?: ('Italian' | 'French')[] | undefined;

  /** Logo */
  logo: Asset;

  /** Owned Deals */
  owned_deals?: IDeal[] | undefined;
}

/** Venues are locations that are owned by a business and will create deals */

export interface IVenue extends Entry<IVenueFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'venue';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE = 'address' | 'business' | 'deal' | 'venue';

export type IEntry = IAddress | IBusiness | IDeal | IVenue;

export type LOCALE_CODE = 'en-AU';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-AU';
